name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - run: pip install twrpdtgen

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install cpio wget
        mkdir dt
      
    - name: Generate random UUID file
      run: |
        RANDOM_NAME=$(uuidgen)
        echo "Generated file name: ${RANDOM_NAME}.img"
        echo "random_filename=${RANDOM_NAME}.img" >> $GITHUB_ENV

    - name: Download boot or recovery img
      run: |
        aria2c "${{ github.event.inputs.IMG_URL }}" -o ${{ env.random_filename }}
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ ./${{ env.random_filename }}
    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
